version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.5
  node-executor:
    working_directory: /tmp
    docker:
      - image: circleci/node:12

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install dependency
          command: pip install -r requirements.txt
      - run:
          name: Django test
          command: python manage.py test
      - run:
          name: Generate swagger artifacts
          command: mkdir -p docs && python manage.py generate_swagger docs/swagger.yaml
      - persist_to_workspace:
          root: docs
          paths:
            - swagger.yaml
  netlify:
    executor:
      name: node-executor
    steps:
      - attach_workspace:
          at: /tmp/docs
      - run:
          name: Echo Test
          command: ls /tmp/docs

workflows:
  ci:
    jobs:
      - build
      - netlify:
          requires:
            - build
