version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.5
  node-executor:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12

jobs:
  build:
    executor:
      name: default
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: Install dependency
          command: pip install -r requirements.txt
      - run:
          name: Django test
          command: python manage.py test
      - run:
          name: Generate swagger artifacts
          command: python manage.py generate_swagger swagger.yaml
      - store_artifacts:
          path: swagger.yaml
          destination: docs/swagger.yaml

workflows:
  ci:
    jobs:
      - build
